---
title: "Project Proposal"
output: html_notebook
---

## Section 1. Introduction
Our team decided to go with the Wine Reviews dataset on Kaggle. This dataset was inspired after the creator watched a documentary on master wine stewards (a person at an expensive restaurant who keeps the wine cellar and advises guests on choices of wine). We plan to use this data to perform an exploratory data analysis.

## Section 2. Data Analysis Plan
Exploratory Questions:

1. What is the best wine? Normalize data based on each user?

2. Best bang for buck wine based on rating?

3. Best wine is the best variety, best wine province, number of wines per province

4. Based on user twitter handle determine location of reviewers

5. Point distribution

6. Most/Least expensive wine

Our intent is to use the following functions:

* join()

* groupBy()

* n()

* mean()

* max()/min()

* summarize()

* filter()

Libraries used:

* ggplot

* rtweet

* tidyverse


### Extra Ideas

* Determine traits of reviews based on tweet (ex: all like basketball)

* Determine best wine given user taste profile (not sure how to do this yet)



## Section 3. Data
The data set is from [kaggle](https://www.kaggle.com/zynicide/wine-reviews). It contains 130,000 reviews of wines from the website [WineEnthusiast](https://www.wineenthusiast.com/).

The character attributes are:

* country: country where the wine is from

* description: description of wine

* designation: vineyard where the grapes were grown
  - 29% null
  
* province: Province or state where wine is from

* region_1: Growing area of grapes (i.e. Napa Valley)
  - 16% null
  
* region_2: If there are more specific places within region_1 (i.e. Rutherford within Napa Valley)
  - 61% null
  
* taster_name: Reviewer's name
  - 20% null
  
* taster_twitter_handle: Reviewer's twitter handle
  - 24% null
  
* title: Title of wine review

* variety: type of grapes used

* winery: winery that made wine

The numeric attributes are:

* price: wine price, per bottle

* points: number of points on a scale of 1-100
